### PR TITLE
Pom fixup

### PR DESCRIPTION
**Pull request by johnmay**
Various fixup of warnings in the POM and JavaDoc errors

### CODE REVIEW

**Comment by johnmay** [comment]
@egonw not sure if you saw this - need to be approved to run GH action. I think will still fail at the signing step but the JavaDoc is now fixed :-)

**Comment by egonw** [comment]
> @egonw not sure if you saw this - need to be approved to run GH action. I think will still fail at the signing step but the JavaDoc is now fixed :-)

indeed I had not... approved for running the tests now

**Comment by egonw** [comment]
@johnmay, do you have more coming or is this release-worthy material?

**Review by egonw — APPROVED** [review]
Looks good to me.

**Comment by johnmay** [comment]
Possibly more coming so don't release for now

**Comment by johnmay** [comment]
But you can merge this

**Comment by egonw** [comment]
Mmm... it doesn't compile locally with Java 11, where I get still more JavaDoc errors, like:

```
[ERROR] /home/egonw/var/Projects/hub/blueobelisk/cmlxom/src/main/java/org/xmlcml/cml/element/CMLAtom.java:632: error: bad use of '>'
[ERROR]      * gets cross products of this->at1 X this->at2
[ERROR]                                    ^
[ERROR] /home/egonw/var/Projects/hub/blueobelisk/cmlxom/src/main/java/org/xmlcml/cml/element/CMLAtom.java:632: error: bad use of '>'
[ERROR]      * gets cross products of this->at1 X this->at2
[ERROR]                                                ^
[ERROR] /home/egonw/var/Projects/hub/blueobelisk/cmlxom/src/main/java/org/xmlcml/cml/element/CMLAtom.java:654: error: bad use of '>'
[ERROR]      * gets cross products of this->at1 X this->at2 the result is a 3D vector
[ERROR]                                    ^
[ERROR] /home/egonw/var/Projects/hub/blueobelisk/cmlxom/src/main/java/org/xmlcml/cml/element/CMLAtom.java:654: error: bad use of '>'
[ERROR]      * gets cross products of this->at1 X this->at2 the result is a 3D vector
[ERROR]                                                ^
[ERROR] /home/egonw/var/Projects/hub/blueobelisk/cmlxom/src/main/java/org/xmlcml/cml/element/CMLAtom.java:699: error: bad use of '>'
[ERROR]      * gets vector this->at1 (i.e. at1 minus this)
[ERROR]                         ^
[ERROR] /home/egonw/var/Projects/hub/blueobelisk/cmlxom/src/main/java/org/xmlcml/cml/element/CMLAtom.java:721: error: bad use of '>'
[ERROR]      * gets vector this->at1 (i.e. at1 minus this)
[ERROR]                         ^
[ERROR] /home/egonw/var/Projects/hub/blueobelisk/cmlxom/src/main/java/org/xmlcml/cml/element/CMLCrystal.java:813: error: bad use of '>'
[ERROR]      * @throws RuntimeException if 0 or >1 nodes
[ERROR]                                         ^
[ERROR] /home/egonw/var/Projects/hub/blueobelisk/cmlxom/src/main/java/org/xmlcml/cml/element/CMLMolecule.java:1396: error: bad use of '>'
[ERROR]          * rounds down (e.g. 3.9996 with epsilon = 0.001 => 3.999, not 4)
[ERROR]                                                           ^
[ERROR] /home/egonw/var/Projects/hub/blueobelisk/cmlxom/src/main/java/org/xmlcml/cml/element/CMLMolecule.java:1433: error: bad use of '>'
[ERROR]          * values (S->1, D->2, T->3)
[ERROR]                      ^
[ERROR] /home/egonw/var/Projects/hub/blueobelisk/cmlxom/src/main/java/org/xmlcml/cml/element/CMLMolecule.java:1433: error: bad use of '>'
[ERROR]          * values (S->1, D->2, T->3)
[ERROR]                            ^
[ERROR] /home/egonw/var/Projects/hub/blueobelisk/cmlxom/src/main/java/org/xmlcml/cml/element/CMLMolecule.java:1433: error: bad use of '>'
[ERROR]          * values (S->1, D->2, T->3)
[ERROR]                                  ^
[ERROR] /home/egonw/var/Projects/hub/blueobelisk/cmlxom/src/main/java/org/xmlcml/cml/element/CMLMolecule.java:1436: error: bad use of '>'
[ERROR]          * 1->S, 2->D 3->T
[ERROR]              ^
[ERROR] /home/egonw/var/Projects/hub/blueobelisk/cmlxom/src/main/java/org/xmlcml/cml/element/CMLMolecule.java:1436: error: bad use of '>'
[ERROR]          * 1->S, 2->D 3->T
[ERROR]                    ^
[ERROR] /home/egonw/var/Projects/hub/blueobelisk/cmlxom/src/main/java/org/xmlcml/cml/element/CMLMolecule.java:1436: error: bad use of '>'
[ERROR]          * 1->S, 2->D 3->T
[ERROR]                         ^
[ERROR] /home/egonw/var/Projects/hub/blueobelisk/cmlxom/src/main/java/org/xmlcml/cml/element/CMLSymmetry.java:330: error: bad use of '>'
[ERROR]      * normalize this translation is normalized to range 0 -> 1-eps iterates
[ERROR]                                                             ^
[ERROR] /home/egonw/var/Projects/hub/blueobelisk/cmlxom/src/main/java/org/xmlcml/cml/element/CMLSymmetry.java:414: error: bad use of '>'
[ERROR]      * @throws RuntimeException if 0 or >1 nodes
[ERROR]                                         ^
[ERROR] /home/egonw/var/Projects/hub/blueobelisk/cmlxom/src/main/java/org/xmlcml/cml/element/CMLVector3.java:265: error: bad use of '>'
[ERROR]      * @return true if this > vector
[ERROR]                             ^
[ERROR] /home/egonw/var/Projects/hub/blueobelisk/cmlxom/src/main/java/org/xmlcml/molutil/Molutils.java:107: error: bad use of '>'
[ERROR]      * @return Point3[] ANY => 1, LINEAR => 2, TRIGONAL => 3, TETRAHEDRAL => 4
[ERROR]                              ^
[ERROR] /home/egonw/var/Projects/hub/blueobelisk/cmlxom/src/main/java/org/xmlcml/molutil/Molutils.java:107: error: bad use of '>'
[ERROR]      * @return Point3[] ANY => 1, LINEAR => 2, TRIGONAL => 3, TETRAHEDRAL => 4
[ERROR]                                           ^
[ERROR] /home/egonw/var/Projects/hub/blueobelisk/cmlxom/src/main/java/org/xmlcml/molutil/Molutils.java:107: error: bad use of '>'
[ERROR]      * @return Point3[] ANY => 1, LINEAR => 2, TRIGONAL => 3, TETRAHEDRAL => 4
[ERROR]                                                          ^
[ERROR] /home/egonw/var/Projects/hub/blueobelisk/cmlxom/src/main/java/org/xmlcml/molutil/Molutils.java:107: error: bad use of '>'
[ERROR]      * @return Point3[] ANY => 1, LINEAR => 2, TRIGONAL => 3, TETRAHEDRAL => 4
[ERROR] /home/egonw/var/Projects/hub/blueobelisk/cmlxom/src/main/java/org/xmlcml/cml/base/CMLElement.java:343: error: bad use of '>'
[ERROR]      * reroutes special cases such as setId() => resetId()
[ERROR]                                                ^
```

I will fix these later, unless you want to do that...

**Comment by johnmay** [comment]
Odd was on Java 17 and thought I got all of them. How many errors?

**Comment by egonw** [comment]
Maybe 50?

**Comment by egonw** [comment]
I've merged it into a 4.1 development branch.

**Pull request closed without merging**
