### PR TITLE
Add unit tests

### PR DESCRIPTION
**Pull request by Sakshi-75**
This is for issue #17 

I've added unit tests for the following files:
1. CMLAction.java
2. CMLActionList.java
3. CMLAtomType.java

The tests also cover methods inherited in these classes from AbstractAction.java, AbstractActionList.java and AbstractAtomType.java respectively.

### CODE REVIEW

**Comment by Sakshi-75** [comment]
Hi @egonw , please review these changes once and share your feedbacks if any. Thanks!

**Comment by egonw** [comment]
@Sakshi-75, I'm travelling right now. I'll look at it asap, likely this weekend.

**Comment by Sakshi-75** [comment]
Sure @egonw , take your time 👍🏻

**Comment by egonw** [comment]
Applied to the `devel/4.7` branch.

**Pull request closed without merging**
